#!/usr/bin/env python3

from __future__ import annotations

import argparse
import subprocess
import sys
import json
import os
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

from llmkb.kb_common import KBContext, ensure_directory, write_json


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the local KB update pipeline.")
    parser.add_argument(
        "--kb-root",
        default=".",
        help="Root directory of the knowledge base.",
    )
    parser.add_argument(
        "--force", action="store_true", help="Force rebuilds in extraction, source pages, and concept pages."
    )
    parser.add_argument("--summarize-books", action="store_true", help="Enable expensive chapter-by-chapter book summarization.")
    parser.add_argument("--doc-id", action="append", default=[], help="Limit the update to selected doc_ids.")
    parser.add_argument(
        "--no-report", action="store_true", help="Disable generation of the ingestion report."
    )
    return parser.parse_args()


def run_step(script: str, args: list[str]) -> str:
    module = f"llmkb.{script.replace('.py', '')}"
    command = [sys.executable, "-m", module, *args]
    print(f"\n>>> Running {module}...")
    result = subprocess.run(command, capture_output=True, text=True, check=False)
    
    # Print output to terminal as well
    if result.stdout:
        print(result.stdout.strip())
    if result.stderr:
        print(result.stderr.strip(), file=sys.stderr)
        
    if result.returncode != 0:
        print(f"Error: {module} failed with return code {result.returncode}")
        
    return result.stdout


def generate_report(context: KBContext, results: dict[str, str]) -> Path | None:
    """Generate a Markdown ingestion report in wiki/logs/."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    file_timestamp = datetime.now().strftime("%Y-%m-%d-%H%M%S")
    
    logs_dir = context.root / "wiki" / "logs"
    ensure_directory(logs_dir)
    
    report_path = logs_dir / f"ingest-{file_timestamp}.md"
    
    lines = [
        f"# Ingestion Report - {timestamp}",
        "",
        "## Summary of Changes",
        "",
    ]
    
    # Try to parse stats from common output formats
    for step, output in results.items():
        if output.strip():
            lines.append(f"### {step.replace('.py', '').title()}")
            lines.append(f"```\n{output.strip()}\n```")
            lines.append("")

    lines.append("---")
    lines.append("*This report was automatically generated by llmkb-update.*")
    
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path


def main() -> None:
    load_dotenv()
    load_dotenv(Path.home() / ".env")
    
    args = parse_args()
    context = KBContext(args.kb_root)
    
    extra_args: list[str] = ["--kb-root", args.kb_root]
    for doc_id in args.doc_id:
        extra_args.extend(["--doc-id", doc_id])
    if args.force:
        extra_args.append("--force")
    if args.summarize_books:
        extra_args.append("--summarize-books")

    results = {}
    
    # 1. Cataloging & Cleaning (Structural)
    results["catalog"] = run_step("catalog_raw.py", ["--kb-root", args.kb_root])
    results["clean"] = run_step("clean_kb.py", ["--kb-root", args.kb_root])
    
    # 2. Extraction & Resolution (Heavy processing)
    results["extract"] = run_step("extract_pages.py", extra_args)
    results["resolve"] = run_step("resolve_near_duplicates.py", extra_args)
    
    # 3. Generation (Wiki creation)
    results["source_pages"] = run_step("build_source_pages.py", extra_args)
    results["concept_pages"] = run_step("build_concept_pages.py", ["--kb-root", args.kb_root])

    if not args.no_report:
        report_path = generate_report(context, results)
        if report_path:
            try:
                display_path = report_path.relative_to(context.root)
            except ValueError:
                display_path = report_path
            print(f"\nIngestion report generated: {display_path}")


if __name__ == "__main__":
    main()
